### PR TITLE
Add a trajectory generator

### LINKED ISSUE #16: Add a Jerk-Limited Trajectory Generator Because Box test is too aggressive
The box test worked but its motion is too aggressive. We need to limit acceleration, velocity, and other rough behaviors. Otherwise offboard mode is scary.

In off board mode, the drone flies with the full responsiveness allowed to pilots. So it can stop on a dime, and accelerate VERY quickly (when descending it looks like it's falling from the sky). This degree of responsiveness exists so that pilots have the best chance of avoiding any problems.

However, an automated mode should fly in a more measured manner. That way, a human pilot has enough time to see what's going on and react, if needed. Only in emergency circumstances is it acceptable for the drone to fly so aggressively in an automated mode. 

Position mode and mission mode use special settings and parameters to limit jerky or fast motion. These limits make it easier for a pilot to take over. These modes limit:
- jerk (3rd time derivative of position)
- acceleration (both vertical and horizontal)
- bank angles
- Rate Limits
- angular acceleration
- max velocity

The specific values assigned for these limits are tuned for the aircraft and its payload.

The software must read the relevant parameters and adjust the set-point animation accordingly.

### PR DESCRIPTION
**Pull request by murphym18**
Fixes #16

### CODE REVIEW

**Comment by murphym18** [comment]
Just finished testing this on the Jetson Nano. This testing was done with PX4 and gazebo running on my desktop and the Jetson was connected to PX4 over the network. Note: it took about 10 minutes to build the docker images. This is because one of the libraries has a C++ implementation that must be built from source on arm.

Here are videos where the Jetson is controlling the drone:
- [the box test while facing west](https://drive.google.com/file/d/1eMYS9582C786-mdIM2Nmn4YEI3ldNprN/view?usp=sharing)
- [test the rc failsafe mid-flight](https://drive.google.com/file/d/1sAxGhVvFC31aundnbaPWhMWvRWwCfNRZ/view?usp=sharing)

**Comment by JaneClelandHuang** [comment]
Michael, what do you mean that it must be built from source *on arm*? We have to build it everytime we arm the drone?  How long does it take each time?

**Comment by tawfiq1200** [comment]
I think he is referring to the ARM architecture of the Jetson.

**Comment by JaneClelandHuang** [comment]
Oh!! Thanks for clarifying Tawfiq.

**Comment by murphym18** [comment]
Very sorry for the confusion. Tawfiq is correct. We must build the ruckig C++ lib when we deploy to ARM CPUs like the one on the Jetson. This only happens once, when we are deploying the software. This would happen indoors while the Jetson has an internet connection. It's completely automated and taken care of by the `docker-compose build` command. This is in contrast to AMD and Intel CPUs where pip installs a pre-built ruckig binary. 

It takes about 10 mins to compile on the Nano. But once the docker images are made, we can re-use them over and over. In the field, the tests take a few seconds to start on the Jetson Nano (but I think it might be faster on the SD-HX10s because the nano is slower).

**Comment by JaneClelandHuang** [comment]
That all sounds fine.  Thanks for getting that problem resolved.

**Comment by murphym18** [comment]
[Fix flight trajectory for smooth motion](https://trello.com/c/cYOy3fJS/2-fix-flight-trajectory-for-smooth-motion)

**Pull request merged**
